# Generated by Django 5.2.4 on 2025-07-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Software', 'Software'), ('Hardware', 'Hardware'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
