# Generated by Django 5.2.4 on 2025-07-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticket_category_ticket_comments_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='client_contact',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='connection_type',
            field=models.CharField(choices=[('Fibre', 'Fibre'), ('Wireless', 'Wireless'), ('Dont Know', 'Dont Know')], default='Dont Know', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
